spring:
  application:
    name: eureka

server:
  port: 8762

eureka:
  instance:
    preferIpAddress: false
    securePortEnabled: false
    nonSecurePortEnabled: true
    securePort: ${server.port}
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${spring.application.name}:${server.port}/eureka